name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install AppleSimulatorUtils
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Install dependencies
      working-directory: ./mobileapp
      run: npm install

    - name: Detox Build
      working-directory: ./mobileapp
      run: npx detox build -c ios.sim.debug

    - name: Detox Test
      working-directory: ./mobileapp
      run: npx detox test -c ios.sim.debug --cleanup
